### ISSUE TITLE
Feature Request: Add a dark mode!

### ISSUE THREAD

**Issue by virtualgeoff** [virtualgeoff/sunclock#3]
Definitely needed!

Ideally would be able to use system settings **or** use the sun elevation.

**Comment by chazchazchaz** [comment]
https://github.com/virtualgeoff/sunclock/pull/4
Added a manual toggle as a starting point

**Comment by virtualgeoff** [comment]
Done. Implemented dark mode and auto mode.
In auto mode the page background matches the color of the current time period. It's a bit garish, so I may tone down the background colors at a later date (use the dark mode colors instead of the light?), but closing for now.
