### ISSUE TITLE
Long tick mark for even numbers

### ISSUE THREAD

**Issue by RomanTatar-wandera** [virtualgeoff/sunclock#5]
Hi,
even numbers(especially 6, 12, 18, 24) are more imprtant, so consider long tickmark when "show hour numbers" is disabled.
Maybe add configuration?

Thank you, this is great tool!

**Comment by virtualgeoff** [comment]
Fixed. I swapped the marks around when hour numbers are hidden (just rotated the long marks around the face by 15º).

Thanks for the suggestion.
